USE MASTER
GO
DROP DATABASE RRHH
GO
CREATE DATABASE RRHH
GO
USE RRHH
GO

CREATE TABLE persona(
	codPersona INT IDENTITY(1,1)  PRIMARY KEY,
	nombres VARCHAR(20)  NOT NULL,
	apellidoPaterno VARCHAR(20)  NOT NULL,
	apellidoMaterno VARCHAR(20)  NOT NULL,
	dni char(8)  NOT NULL  UNIQUE ,
	telefono CHAR(9)  NOT NULL,
    nacimiento	DATE  NOT NULL,
    sexo	VARCHAR(1)  NOT NULL,
    email VARCHAR(20)  NOT NULL,

	CONSTRAINT CK_PERSONA CHECK(sexo = 'M' OR sexo = 'F')
)

GO

CREATE TABLE profesion_oficio(
	codProfesion TINYINT IDENTITY(1,1) PRIMARY KEY   ,
	profesion VARCHAR(20)  NOT NULL unique
) 

GO

CREATE TABLE  red (
	codRed	TINYINT IDENTITY(1,1)  PRIMARY KEY,
	red	VARCHAR(20)  NOT NULL
)

GO

CREATE TABLE microred (
	codMicro	SMALLINT IDENTITY(1,1) PRIMARY KEY ,
	microred	VARCHAR(200)  NOT NULL ,
	red	TINYINT  NOT NULL,
	 
	CONSTRAINT fk_red_microred FOREIGN KEY (red)
	REFERENCES red(codRed) ON update CASCADE ON DELETE CASCADE

)

GO

CREATE TABLE establecimiento(
	codEstab SMALLINT IDENTITY(1,1)  PRIMARY KEY ,
	establecimiento VARCHAR(200)  NOT NULL,
	microred SMALLINT  NOT NULL,
	
	CONSTRAINT fk_microred_establecimiento FOREIGN KEY (microred)
	REFERENCES microred(codMicro) ON UPDATE CASCADE ON DELETE CASCADE 
	
)

GO

CREATE TABLE estadoContrato(
	codEstadoCon TINYINT IDENTITY(1,1)  PRIMARY KEY ,
	nomEst VARCHAR(50)  NOT NULL
)

GO

CREATE TABLE cargo(
	codCargo TINYINT IDENTITY(1,1)  PRIMARY KEY ,
	nomCargo VARCHAR(50)  NOT NULL
) 

GO

CREATE TABLE funcionesCargo (
	codFuncion TINYINT  PRIMARY KEY ,
	nomFuncion VARCHAR(200)  NOT NULL,
	cargo TINYINT NOT NULL,
	
	CONSTRAINT FK_CARGO_FUNCIONES FOREIGN KEY (cargo)
	REFERENCES cargo(codCargo) ON UPDATE CASCADE ON DELETE CASCADE 
)

GO

CREATE TABLE tipoContrato(
	codTipoCont TINYINT IDENTITY(1,1)  PRIMARY KEY ,
	nomTipoCont VARCHAR(50)  NOT NULL
)

GO

CREATE TABLE contratoCabecera(
	codContrato INT  IDENTITY(1,1) PRIMARY KEY ,
	nivel VARCHAR(88)  NULL,
	fechaInicio DATE  NOT NULL,
	fechaFin DATE  NOT NULL,
	memoGeresa VARCHAR(8)   NULL,
	persona INT  NOT NULL,
	estadoCont TINYINT  NOT NULL,
	profesion TINYINT  NOT NULL,
	cargo	TINYINT  NOT NULL,
	tipoCont TINYINT  NOT NULL,
	
	CONSTRAINT FK_PERSONA_CONTRATOCAB FOREIGN KEY (persona)
	REFERENCES persona(codPersona) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_ESTADOCONT_CONTRATOCAB FOREIGN KEY (estadoCont)
	REFERENCES estadoContrato(codEstadoCon) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_PROFESION_CONTRATOCAB FOREIGN KEY (profesion)
	REFERENCES profesion_oficio(codProfesion) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_CARGO_CONTRATOCAB FOREIGN KEY (cargo)
	REFERENCES cargo(codCargo) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_TIPOCONT_CONTRATOCAB FOREIGN KEY (tipoCont)
	REFERENCES tipoContrato(codTipoCont) ON UPDATE CASCADE ON DELETE CASCADE
	
	
)

GO

/*
* cada vez que se genere un desplazamiento se guardara en esta tabla
* y la columna estado solo aceptara valores 0 y 1 donde el 1=activo 0 = inactivo
*/

CREATE TABLE contratoDetalle(
	codDetalleCont	INT IDENTITY(1,1)  PRIMARY KEY ,
	estado	VARCHAR(1)  NOT NULL ,
	codContrato	INT  NOT NULL,
	codEstab SMALLINT NOT NULL,
		
	CONSTRAINT FK_CONTRATO_DETALLECONTR FOREIGN KEY (codContrato)
	REFERENCES contratoCabecera(codContrato) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_ESTABLECIMIENTO_DETALLECONTR FOREIGN KEY (codEstab)
	REFERENCES establecimiento(codEstab) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT CK_CONTRATO_DETALLE CHECK(estado = 1 OR estado = 0)
)

GO

CREATE TABLE tipoLicencia(
	codTipoLic TINYINT IDENTITY(1,1)  PRIMARY KEY ,
	nomTipoLic VARCHAR(15)  NOT NULL
)

GO

CREATE TABLE licencia(
	codLicencia INT IDENTITY(1,1)  PRIMARY KEY ,
	fechaInicio DATE  NOT NULL,
	fechaFin DATE  NOT NULL,
	observacion VARCHAR(50)  NOT NULL,
	documento VARCHAR(20)  NOT NULL,
	codTipoLic TINYINT NOT NULL,
	codContrato INT NOT NULL,

	
	CONSTRAINT FK_TIPOLIC_LICENCIA FOREIGN KEY (codTipoLic)
	REFERENCES tipoLicencia(codTipoLic) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_CONTRATO_LICENCIA FOREIGN KEY (codContrato)
	REFERENCES contratoCabecera(codContrato) ON UPDATE CASCADE ON DELETE CASCADE
)

GO

CREATE TABLE motivoRetiro(
	codMotivoR TINYINT IDENTITY(1,1) PRIMARY KEY ,
	nomMotivo VARCHAR(20)  NOT NULL
)

GO

CREATE TABLE retiro(
  codRetiro  INT IDENTITY(1,1)  PRIMARY KEY ,
  fechaRetiro DATE  NOT NULL,
  codContrato INT ,
  codMotivoR TINYINT ,
  
  CONSTRAINT FK_CONTRATO_RETIRO FOREIGN KEY (codContrato)
  REFERENCES contratoCabecera(codContrato) ON UPDATE CASCADE ON DELETE CASCADE,
  
  CONSTRAINT FK_MOTIVO_RETIRO FOREIGN KEY (codMotivoR)
  REFERENCES motivoRetiro(codMotivoR) ON UPDATE CASCADE ON DELETE CASCADE
  
) 

GO

CREATE TABLE motivoSuspension(
	codMotivoSus TINYINT IDENTITY(1,1) PRIMARY KEY ,
	nomMotivo VARCHAR(20)  NOT NULL
)

GO

CREATE TABLE suspension(
  codSuspension INT IDENTITY(1,1)  PRIMARY KEY ,
  fechaSuspension DATE  NOT NULL,
  codContrato INT NOT NULL,
  codMotivoSus TINYINT NOT NULL,
  
  
  CONSTRAINT FK_CONTRATO_SUSPENSION FOREIGN KEY (codContrato)
  REFERENCES contratoCabecera(codContrato) ON UPDATE CASCADE ON DELETE CASCADE,
  
  CONSTRAINT FK_MOTIVO_SUSPENSION FOREIGN KEY (codMotivoSus)
  REFERENCES motivoSuspension(codMotivoSus) ON UPDATE CASCADE ON DELETE CASCADE
  
) 

GO

CREATE TABLE rol (
	codRol TINYINT IDENTITY(1,1)  PRIMARY KEY ,
	nomRol VARCHAR(10)  NOT NULL
)

GO

CREATE TABLE accesos (
	codAcces	TINYINT IDENTITY(1,1) PRIMARY KEY ,
	nomVista	VARCHAR(10)  NOT NULL,
	codRol	TINYINT  NOT NULL,
	
	CONSTRAINT FK_ROL_ACCESO FOREIGN KEY (codRol)
	REFERENCES rol(codRol) ON UPDATE CASCADE ON DELETE CASCADE

)

GO

CREATE TABLE usuario(
	codUsuario TINYINT IDENTITY(1,1) PRIMARY KEY ,
	usuario VARCHAR(20)  NOT NULL,
	contrase VARCHAR(250) NOT NULL,
	
	codRol TINYINT NOT NULL,
	codPersona INT NOT NULL,
	
	CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (codRol)
	REFERENCES rol(codRol) ON UPDATE CASCADE ON DELETE CASCADE,
	
	CONSTRAINT FK_PERSONA_USUARIO FOREIGN KEY (codPersona)
	REFERENCES persona(codPersona) ON UPDATE CASCADE ON DELETE CASCADE
)
